[package]
name = "host-hq-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
postcard = { version = "1.1.3", default-features = false, features = [
    "use-std",
] }
serde = { version = "1", features = ["derive"] }
