[package]
name = "oci-sdk-generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oci-gen"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tera = "1"
heck = "0.5"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
