[package]
name = "measure-cpu-time"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time", "sync", "test-util"] }
