[package]
name = "e4"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
deno_core = "0.376.0"
futures = "0.3.31"
hyper = "1.8.1"
reqwest = { version = "0.12.28", default-features = false, features = [
    "rustls-tls",
] }
tokio = { version = "1.48.0", features = ["full"] }
