[package]
name = "doc-db"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
libsql.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
